### ISSUE TITLE
core service build broken

### ISSUE THREAD

**Issue by deardooley** [TACC/abaco#14]
> The images in the Docker Registry build fine, but they are not produced from an automated build, so I'm not sure where they're coming from or whether they reflect the current head in this repo.

The image builds fine. When running via Docker Toolbox on Yosemite, the admin and message apis fail due to an issue in the underlying Flash dependencies. Google seems to think it's a Python version compatibility. Here is my setup and log info. 

Docker daemon

``` bash
$ docker info
Containers: 14
Images: 486
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 514
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: XXN6:UBNG:JWHG:GQGL:IW3Z:CMRK:PU7C:XROS:DEVN:PPXU:J2O4:KL3A
Debug mode (server): true
File Descriptors: 33
Goroutines: 77
System Time: 2015-11-09T01:36:40.657932324Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: deardooley
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

Docker Compose version:  

``` bash
$ docker-compose -v
docker-compose version: 1.4.0
```

Docker build logs:  

``` bash
$ docker build --rm=true -t jstubbs/abaco_core .
Sending build context to Docker daemon 366.6 kB
Step 0 : FROM alpine:3.2
 ---> f4fddc471ec2
Step 1 : RUN apk add --update musl python3 && rm /var/cache/apk/*
 ---> Running in 95e23743d3c3
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/6) Installing libbz2 (1.0.6-r3)
(2/6) Installing libffi (3.2.1-r0)
(3/6) Installing ncurses-terminfo-base (5.9-r3)
(4/6) Installing ncurses-widec-libs (5.9-r3)
(5/6) Installing sqlite-libs (3.8.10.2-r0)
(6/6) Installing python3 (3.4.3-r2)
Executing busybox-1.23.2-r0.trigger
OK: 55 MiB in 21 packages
 ---> 0cd0db9ee740
Removing intermediate container 95e23743d3c3
Step 2 : RUN apk add --update bash && rm -f /var/cache/apk/*
 ---> Running in 7e68151bc9e4
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/3) Installing ncurses-libs (5.9-r3)
(2/3) Installing readline (6.3.008-r0)
(3/3) Installing bash (4.3.33-r0)
Executing busybox-1.23.2-r0.trigger
OK: 56 MiB in 24 packages
 ---> e2a68b5d8e77
Removing intermediate container 7e68151bc9e4
Step 3 : RUN apk add --update git && rm -f /var/cache/apk/*
 ---> Running in c8b2c86bc586
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/11) Installing run-parts (4.4-r0)
(2/11) Installing openssl (1.0.2d-r0)
(3/11) Installing lua5.2-libs (5.2.4-r0)
(4/11) Installing lua5.2 (5.2.4-r0)
(5/11) Installing lua5.2-posix (33.3.1-r2)
(6/11) Installing ca-certificates (20141019-r2)
(7/11) Installing libssh2 (1.5.0-r0)
(8/11) Installing curl (7.42.1-r0)
(9/11) Installing expat (2.1.0-r1)
(10/11) Installing pcre (8.37-r1)
(11/11) Installing git (2.4.1-r0)
Executing busybox-1.23.2-r0.trigger
Executing ca-certificates-20141019-r2.trigger
OK: 73 MiB in 35 packages
 ---> 588a7086fde7
Removing intermediate container c8b2c86bc586
Step 4 : RUN apk add --update g++ -f /var/cache/apk/*
 ---> Running in a7ef117082c9
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/16) Installing libgcc (4.9.2-r5)
(2/16) Installing libstdc++ (4.9.2-r5)
(3/16) Installing binutils-libs (2.25-r3)
(4/16) Installing binutils (2.25-r3)
(5/16) Installing libgomp (4.9.2-r5)
(6/16) Installing pkgconf (0.9.11-r0)
(7/16) Installing pkgconfig (0.25-r1)
(8/16) Installing gmp (6.0.0a-r0)
(9/16) Installing mpfr3 (3.1.2-r0)
(10/16) Installing mpc1 (1.0.1-r0)
(11/16) Installing gcc (4.9.2-r5)
(12/16) Installing musl-dbg (1.1.11-r2)
(13/16) Installing libc6-compat (1.1.11-r2)
(14/16) Installing musl-dev (1.1.11-r2)
(15/16) Installing libc-dev (0.7-r0)
(16/16) Installing g++ (4.9.2-r5)
Executing busybox-1.23.2-r0.trigger
OK: 197 MiB in 51 packages
 ---> 83bb9ca81428
Removing intermediate container a7ef117082c9
Step 5 : RUN apk add --update python3-dev -f /var/cache/apk/*
 ---> Running in 8d6070c2c740
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/3) Installing python3-doc (3.4.3-r2)
(2/3) Installing python3-tests (3.4.3-r2)
(3/3) Installing python3-dev (3.4.3-r2)
Executing busybox-1.23.2-r0.trigger
OK: 255 MiB in 54 packages
 ---> b405e6129a1c
Removing intermediate container 8d6070c2c740
Step 6 : ADD actors/requirements.txt /requirements.txt
 ---> 40a83b96dce9
Removing intermediate container d6f00812c437
Step 7 : RUN pip3 install -r /requirements.txt
 ---> Running in 9598e2892fd9
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Obtaining channelpy from git+git://github.com/TACC/channelpy.git#egg=channelpy (from -r /requirements.txt (line 1))
  Cloning git://github.com/TACC/channelpy.git to /src/channelpy
Collecting flask==0.10.1 (from -r /requirements.txt (line 2))
  Downloading Flask-0.10.1.tar.gz (544kB)
Collecting Flask-RESTful==0.3.3 (from -r /requirements.txt (line 3))
  Downloading Flask_RESTful-0.3.3-py2.py3-none-any.whl
Collecting redis==2.10.3 (from -r /requirements.txt (line 4))
  Downloading redis-2.10.3.tar.gz (86kB)
Collecting pika==0.9.13 (from -r /requirements.txt (line 5))
  Downloading pika-0.9.13.tar.gz (63kB)
Collecting docker-py (from -r /requirements.txt (line 6))
  Downloading docker-py-1.5.0.tar.gz (59kB)
Collecting pycrypto==2.6.1 (from -r /requirements.txt (line 7))
  Downloading pycrypto-2.6.1.tar.gz (446kB)
Collecting PyJWT==0.2.3 (from -r /requirements.txt (line 8))
  Downloading PyJWT-0.2.3-py2.py3-none-any.whl
Collecting rabbitpy (from channelpy->-r /requirements.txt (line 1))
  Downloading rabbitpy-0.26.2-py2.py3-none-any.whl (47kB)
Collecting pytest (from channelpy->-r /requirements.txt (line 1))
  Downloading pytest-2.8.2-py2.py3-none-any.whl (149kB)
Collecting six (from channelpy->-r /requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting PyYAML (from channelpy->-r /requirements.txt (line 1))
  Downloading PyYAML-3.11.tar.gz (248kB)
Collecting Werkzeug>=0.7 (from flask==0.10.1->-r /requirements.txt (line 2))
  Downloading Werkzeug-0.11-py2.py3-none-any.whl (304kB)
Collecting Jinja2>=2.4 (from flask==0.10.1->-r /requirements.txt (line 2))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Collecting itsdangerous>=0.21 (from flask==0.10.1->-r /requirements.txt (line 2))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting aniso8601>=0.82 (from Flask-RESTful==0.3.3->-r /requirements.txt (line 3))
  Downloading aniso8601-1.1.0.tar.gz (49kB)
Collecting pytz (from Flask-RESTful==0.3.3->-r /requirements.txt (line 3))
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB)
Collecting requests>=2.5.2 (from docker-py->-r /requirements.txt (line 6))
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
Collecting websocket-client>=0.32.0 (from docker-py->-r /requirements.txt (line 6))
  Downloading websocket_client-0.34.0.tar.gz (193kB)
Collecting pamqp<2.0,>=1.6.1 (from rabbitpy->channelpy->-r /requirements.txt (line 1))
  Downloading pamqp-1.6.1-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest->channelpy->-r /requirements.txt (line 1))
  Downloading py-1.4.30-py2.py3-none-any.whl (81kB)
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.10.1->-r /requirements.txt (line 2))
  Downloading MarkupSafe-0.23.tar.gz
Collecting python-dateutil (from aniso8601>=0.82->Flask-RESTful==0.3.3->-r /requirements.txt (line 3))
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
Installing collected packages: python-dateutil, MarkupSafe, py, pamqp, websocket-client, requests, pytz, aniso8601, itsdangerous, Jinja2, Werkzeug, PyYAML, six, pytest, rabbitpy, PyJWT, pycrypto, docker-py, pika, redis, Flask-RESTful, flask, channelpy

  Running setup.py install for MarkupSafe
    building 'markupsafe._speedups' extension
    gcc -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Os -fomit-frame-pointer -fPIC -I/usr/include/python3.4m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.4/markupsafe/_speedups.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/markupsafe/_speedups.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/markupsafe/_speedups.cpython-34m.so


  Running setup.py install for websocket-client
    changing mode of build/scripts-3.4/wsdump.py from 644 to 755
    changing mode of /usr/bin/wsdump.py to 755


  Running setup.py install for aniso8601
  Running setup.py install for itsdangerous


  Running setup.py install for PyYAML
    checking if libyaml is compilable
    gcc -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Os -fomit-frame-pointer -fPIC -I/usr/include/python3.4m -c build/temp.linux-x86_64-3.4/check_libyaml.c -o build/temp.linux-x86_64-3.4/check_libyaml.o
    build/temp.linux-x86_64-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)




  Running setup.py install for pycrypto
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for __gmpz_init in -lgmp... no
    checking for __gmpz_init in -lmpir... no
    checking whether mpz_powm is declared... no
    checking whether mpz_powm_sec is declared... no
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for inttypes.h... (cached) yes
    checking limits.h usability... yes
    checking limits.h presence... yes
    checking for limits.h... yes
    checking stddef.h usability... yes
    checking stddef.h presence... yes
    checking for stddef.h... yes
    checking for stdint.h... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking wchar.h usability... yes
    checking wchar.h presence... yes
    checking for wchar.h... yes
    checking for inline... inline
    checking for int16_t... yes
    checking for int32_t... yes
    checking for int64_t... yes
    checking for int8_t... yes
    checking for size_t... yes
    checking for uint16_t... yes
    checking for uint32_t... yes
    checking for uint64_t... yes
    checking for uint8_t... yes
    checking for stdlib.h... (cached) yes
    checking for GNU libc compatible malloc... yes
    checking for memmove... yes
    checking for memset... yes
    configure: creating ./config.status
    config.status: creating src/config.h
    building 'Crypto.Hash._MD2' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/MD2.c -o build/temp.linux-x86_64-3.4/src/MD2.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/MD2.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_MD2.cpython-34m.so
    building 'Crypto.Hash._MD4' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/MD4.c -o build/temp.linux-x86_64-3.4/src/MD4.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/MD4.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_MD4.cpython-34m.so
    building 'Crypto.Hash._SHA256' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/SHA256.c -o build/temp.linux-x86_64-3.4/src/SHA256.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/SHA256.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_SHA256.cpython-34m.so
    building 'Crypto.Hash._SHA224' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/SHA224.c -o build/temp.linux-x86_64-3.4/src/SHA224.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/SHA224.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_SHA224.cpython-34m.so
    building 'Crypto.Hash._SHA384' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/SHA384.c -o build/temp.linux-x86_64-3.4/src/SHA384.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/SHA384.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_SHA384.cpython-34m.so
    building 'Crypto.Hash._SHA512' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/SHA512.c -o build/temp.linux-x86_64-3.4/src/SHA512.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/SHA512.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_SHA512.cpython-34m.so
    building 'Crypto.Hash._RIPEMD160' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -DPCT_LITTLE_ENDIAN=1 -Isrc/ -I/usr/include/python3.4m -c src/RIPEMD160.c -o build/temp.linux-x86_64-3.4/src/RIPEMD160.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/RIPEMD160.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Hash/_RIPEMD160.cpython-34m.so
    building 'Crypto.Cipher._AES' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/AES.c -o build/temp.linux-x86_64-3.4/src/AES.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/AES.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_AES.cpython-34m.so
    building 'Crypto.Cipher._ARC2' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/ARC2.c -o build/temp.linux-x86_64-3.4/src/ARC2.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/ARC2.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_ARC2.cpython-34m.so
    building 'Crypto.Cipher._Blowfish' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/Blowfish.c -o build/temp.linux-x86_64-3.4/src/Blowfish.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/Blowfish.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_Blowfish.cpython-34m.so
    building 'Crypto.Cipher._CAST' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/CAST.c -o build/temp.linux-x86_64-3.4/src/CAST.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/CAST.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_CAST.cpython-34m.so
    building 'Crypto.Cipher._DES' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -Isrc/libtom/ -I/usr/include/python3.4m -c src/DES.c -o build/temp.linux-x86_64-3.4/src/DES.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/DES.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_DES.cpython-34m.so
    building 'Crypto.Cipher._DES3' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -Isrc/libtom/ -I/usr/include/python3.4m -c src/DES3.c -o build/temp.linux-x86_64-3.4/src/DES3.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/DES3.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_DES3.cpython-34m.so
    building 'Crypto.Cipher._ARC4' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/ARC4.c -o build/temp.linux-x86_64-3.4/src/ARC4.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/ARC4.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_ARC4.cpython-34m.so
    building 'Crypto.Cipher._XOR' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/XOR.c -o build/temp.linux-x86_64-3.4/src/XOR.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/XOR.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Cipher/_XOR.cpython-34m.so
    building 'Crypto.Util.strxor' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/strxor.c -o build/temp.linux-x86_64-3.4/src/strxor.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/strxor.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Util/strxor.cpython-34m.so
    building 'Crypto.Util._counter' extension
    gcc -Wno-unused-result -fwrapv -Wall -Wstrict-prototypes -fomit-frame-pointer -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python3.4m -c src/_counter.c -o build/temp.linux-x86_64-3.4/src/_counter.o
    gcc -shared -Wl,--as-needed build/temp.linux-x86_64-3.4/src/_counter.o -L/usr/lib -lpython3.4m -o build/lib.linux-x86_64-3.4/Crypto/Util/_counter.cpython-34m.so
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
  Running setup.py install for docker-py
  Running setup.py install for pika
  Running setup.py install for redis

  Running setup.py install for flask
  Running setup.py develop for channelpy
    Creating /usr/lib/python3.4/site-packages/channelpy.egg-link (link to .)
    Adding channelpy 0.2 to easy-install.pth file
    Installed /src/channelpy
Successfully installed Flask-RESTful-0.3.3 Jinja2-2.8 MarkupSafe-0.23 PyJWT-0.2.3 PyYAML-3.11 Werkzeug-0.11 aniso8601-1.1.0 channelpy docker-py-1.5.0 flask-0.10.1 itsdangerous-0.24 pamqp-1.6.1 pika-0.9.13 py-1.4.30 pycrypto-2.6.1 pytest-2.8.2 python-dateutil-2.4.2 pytz-2015.7 rabbitpy-0.26.2 redis-2.10.3 requests-2.8.1 six-1.10.0 websocket-client-0.34.0
 ---> 4445768e3634
Removing intermediate container 9598e2892fd9
Step 8 : ADD abaco.conf /etc/abaco.conf
 ---> 09730e4640f9
Removing intermediate container 3ef3f4d9b638
Step 9 : ADD actors /actors
 ---> 8529a438e53a
Removing intermediate container 243277df6000
Step 10 : ADD entry.sh /entry.sh
 ---> f97dca57f57d
Removing intermediate container 3698d9190965
Step 11 : RUN chmod +x /entry.sh
 ---> Running in 79d7d10f9416
 ---> 7b6d74decc80
Removing intermediate container 79d7d10f9416
Step 12 : EXPOSE 5000
 ---> Running in 23084bc683b2
 ---> 8d81dd16f223
Removing intermediate container 23084bc683b2
Step 13 : CMD ./entry.sh
 ---> Running in e1238ba90d30
 ---> 098eb584d679
Removing intermediate container e1238ba90d30
Successfully built 098eb584d679
```

Docker Compose instantiation logs:  

`````` bash
$ docker-compose -f docker-compose-local.yml up
Creating abaco_nginx_1...
Creating abaco_rabbit_1...
Creating abaco_redis_1...
Creating abaco_spawner_1...
Creating abaco_admin_1...
Creating abaco_mes_1...
Creating abaco_reg_1...
Attaching to abaco_nginx_1, abaco_rabbit_1, abaco_redis_1, abaco_spawner_1, abaco_admin_1, abaco_mes_1, abaco_reg_1
redis_1   | 1:C 09 Nov 01:23:37.621 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1   |                 _._                                                  
redis_1   |            _.-``__ ''-._                                             
redis_1   |       _.-``    `.  `_.  ''-._           Redis 3.0.5 (00000000/0) 64 bit
redis_1   |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1   |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1   |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1   |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1   |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1   |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1   |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1   |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1   |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1   |  |    `-._`-._        _.-'_.-'    |                                  
redis_1   |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1   |       `-._    `-.__.-'    _.-'                                       
redis_1   |           `-._        _.-'                                           
redis_1   |               `-.__.-'                                               
redis_1   | 
redis_1   | 1:M 09 Nov 01:23:37.624 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 09 Nov 01:23:37.624 # Server started, Redis version 3.0.5
redis_1   | 1:M 09 Nov 01:23:37.624 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1   | 1:M 09 Nov 01:23:37.624 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1   | 1:M 09 Nov 01:23:37.624 * The server is now ready to accept connections on port 6379
rabbit_1  | 
rabbit_1  |               RabbitMQ 3.5.3. Copyright (C) 2007-2014 GoPivotal, Inc.
rabbit_1  |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
rabbit_1  |   ##  ##
rabbit_1  |   ##########  Logs: tty
rabbit_1  |   ######  ##        tty
rabbit_1  |   ##########
rabbit_1  |               Starting broker...
rabbit_1  | =INFO REPORT==== 9-Nov-2015::01:23:39 ===
rabbit_1  | Starting RabbitMQ 3.5.3 on Erlang 17.5.3
rabbit_1  | Copyright (C) 2007-2014 GoPivotal, Inc.
rabbit_1  | Licensed under the MPL.  See http://www.rabbitmq.com/
rabbit_1  | 
rabbit_1  | =INFO REPORT==== 9-Nov-2015::01:23:39 ===
rabbit_1  | node           : abaco-rabbit@3d15b54d7b6b
rabbit_1  | home dir       : /var/lib/rabbitmq
rabbit_1  | config file(s) : /etc/rabbitmq/rabbitmq.config
rabbit_1  | cookie hash    : Di4rqcuayMGOy+h/gO2vnQ==
rabbit_1  | log            : tty
rabbit_1  | sasl log       : tty
rabbit_1  | database dir   : /var/lib/rabbitmq/mnesia/abaco-rabbit
admin_1   |  * Restarting with stat
mes_1     |  * Restarting with stat
reg_1     |  * Restarting with stat
mes_1     |  * Debugger is active!
mes_1     | Traceback (most recent call last):
mes_1     |   File "/actors/message_api.py", line 21, in <module>
mes_1     |     app.run(host='0.0.0.0', debug=True)
mes_1     |   File "/usr/lib/python3.4/site-packages/flask/app.py", line 772, in run
mes_1     |     run_simple(host, port, self, **options)
mes_1     |   File "/usr/lib/python3.4/site-packages/werkzeug/serving.py", line 633, in run_simple
mes_1     |     application = DebuggedApplication(application, use_evalex)
mes_1     |   File "/usr/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 169, in __init__
mes_1     |     if self.pin is None:
mes_1     |   File "/usr/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 179, in _get_pin
mes_1     |     self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
mes_1     |   File "/usr/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 96, in get_pin_and_cookie_name
mes_1     |     h.update('cookiesalt')
mes_1     | TypeError: Unicode-objects must be encoded before hashing
admin_1   |  * Debugger is active!
admin_1   | Traceback (most recent call last):
admin_1   |   File "/actors/admin_api.py", line 22, in <module>
admin_1   |     app.run(host='0.0.0.0', debug=True)
admin_1   |   File "/usr/lib/python3.4/site-packages/flask/app.py", line 772, in run
admin_1   |     run_simple(host, port, self, **options)
admin_1   |   File "/usr/lib/python3.4/site-packages/werkzeug/serving.py", line 633, in run_simple
admin_1   |     application = DebuggedApplication(application, use_evalex)
admin_1   |   File "/usr/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 169, in __init__
admin_1   |     if self.pin is None:
admin_1   |   File "/usr/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 179, in _get_pin
admin_1   |     self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
admin_1   |   File "/usr/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 96, in get_pin_and_cookie_name
admin_1   |     h.update('cookiesalt')
admin_1   | TypeError: Unicode-objects must be encoded before hashing
abaco_mes_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping abaco_reg_1... done
Stopping abaco_admin_1... done
Stopping abaco_spawner_1... done
Stopping abaco_redis_1... done
Stopping abaco_rabbit_1... done
Stopping abaco_nginx_1... done
``````

**Comment by joestubbs** [comment]
Interesting, I'll have to dig deeper. Are you saying that everything works fine when you run with the images from the hub? Those are built directly from HEAD in this repo; I pushed a version earlier today and the most recent version just now.

**Comment by deardooley** [comment]
yes. the only thing I didn’t include in the above listings was the `git clone https://github.com/TACC/abaco.git` command.

—
Rion
